### ISSUE TITLE
Consider a better error message if dev failed to build npm

### ISSUE THREAD

**Issue by jasonkholden** [man-group/dtale#105]
I didn't read the docs closely enough, and got a fairly obtuse error when I tried to run detail after just running python setup.py develop, and didn't run npm build (correctly documented at https://github.com/man-group/dtale#for-developers)

Maybe we should raise a more informative error than below?
In [1]: import dtale                                                            

In [2]: import pandas as pd                                                     

In [3]: df = pd.DataFrame([dict(a=1,b=2,c=3)])                                  

In [4]: d = dtale.show(df)                                                      

In [5]: d.open_browser()                                                        

In [6]: [5319:5319:0309/081036.267082:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
2020-03-09 08:10:36,784 - ERROR    - 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/jason/virt-dtale/lib/python3.6/site-packages/Flask-1.1.1-py3.6.egg/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/jason/virt-dtale/lib/python3.6/site-packages/Flask-1.1.1-py3.6.egg/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/jason/virt-dtale/lib/python3.6/site-packages/Flask-1.1.1-py3.6.egg/flask/helpers.py", line 1082, in send_static_file
    self.static_folder, filename, cache_timeout=cache_timeout
  File "/home/jason/virt-dtale/lib/python3.6/site-packages/Flask-1.1.1-py3.6.egg/flask/helpers.py", line 767, in send_from_directory
    raise NotFound()

**Comment by aschonfeld** [comment]
v1.7.15
