### ISSUE TITLE
Can't open charts

### ISSUE THREAD

**Issue by eloneill** [man-group/dtale#180]
When I open the chart page I get a blank page:
![image](https://user-images.githubusercontent.com/10655016/79483413-ea128580-7fd7-11ea-8bff-841fab5dde5c.png)

and then this error in the jupyter notebook:

`Exception on /charts/_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 967, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 902, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "C:\ProgramData\Anaconda3\lib\site-packages\dtale\dash_application\views.py", line 467, in display_page
    data_id = get_data_id(pathname)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dtale\dash_application\views.py", line 84, in get_data_id
    return pathname.split('/')[-1]
AttributeError: 'NoneType' object has no attribute 'split'`

Any help is appreciated!

**Comment by aschonfeld** [comment]
Sorry about that, looks like dash released a new version recently which broke the charts page.  If you downgrade dash to 1.10.0 it will fix this.  Hopefully should have an update in the next few days to fix this.

**Comment by eloneill** [comment]
That did the trick! Thank you!

**Comment by aschonfeld** [comment]
@eloneill I have just released v1.8.9 which will have the fix for the latest version of plotly/dash in case you really wanted the latest version.  Enjoy!
