### ISSUE TITLE
Trendline with new scipy not working

### ISSUE THREAD

**Issue by SmokinCaterpillar** [man-group/dtale#278]
Selecting any trendline in scatter plots fails with an ImportError upon importing `factorial` from `scipy.misc`, see stacktrace below.

Reason is that `factorial` moved (since >1.2.1, I think) from `scipy.misc` to `scipy.special`, see [HERE](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.factorial.html#:~:text=Factorial%20of%20n%2C%20as%20integer,int64%20or%20object%20if%20necessary.).

```
Traceback (most recent call last):
  File "/home/robert/anaconda3/envs/prism/lib/python3.7/site-packages/dtale/dash_application/charts.py", line 2697, in build_chart
    data, x, y, axes_builder, chart_builder, **kwargs
  File "/home/robert/anaconda3/envs/prism/lib/python3.7/site-packages/dtale/dash_application/charts.py", line 651, in scatter_builder
    return [_build_final_scatter(y2) for y2 in y]
  File "/home/robert/anaconda3/envs/prism/lib/python3.7/site-packages/dtale/dash_application/charts.py", line 651, in <listcomp>
    return [_build_final_scatter(y2) for y2 in y]
  File "/home/robert/anaconda3/envs/prism/lib/python3.7/site-packages/dtale/dash_application/charts.py", line 615, in _build_final_scatter
    "data": list(_build_data()),
  File "/home/robert/anaconda3/envs/prism/lib/python3.7/site-packages/dtale/dash_application/charts.py", line 612, in _build_data
    yield build_scatter_trendline(d["x"], d[y_val], trendline)
  File "/home/robert/anaconda3/envs/prism/lib/python3.7/site-packages/dtale/dash_application/charts.py", line 525, in build_scatter_trendline
    fig = px.scatter(x=x, y=y, trendline=trendline)
  File "/home/robert/anaconda3/envs/prism/lib/python3.7/site-packages/plotly/express/_chart_types.py", line 64, in scatter
    return make_figure(args=locals(), constructor=go.Scatter)
  File "/home/robert/anaconda3/envs/prism/lib/python3.7/site-packages/plotly/express/_core.py", line 1987, in make_figure
    args, trace_spec, group, mapping_labels.copy(), sizeref
  File "/home/robert/anaconda3/envs/prism/lib/python3.7/site-packages/plotly/express/_core.py", line 283, in make_trace_kwargs
    import statsmodels.api as sm
  File "/home/robert/anaconda3/envs/prism/lib/python3.7/site-packages/statsmodels/api.py", line 16, in <module>
    from .discrete.discrete_model import (Poisson, Logit, Probit,
  File "/home/robert/anaconda3/envs/prism/lib/python3.7/site-packages/statsmodels/discrete/discrete_model.py", line 45, in <module>
    from statsmodels.distributions import genpoisson_p
  File "/home/robert/anaconda3/envs/prism/lib/python3.7/site-packages/statsmodels/distributions/__init__.py", line 2, in <module>
    from .edgeworth import ExpandedNormal
  File "/home/robert/anaconda3/envs/prism/lib/python3.7/site-packages/statsmodels/distributions/edgeworth.py", line 7, in <module>
    from scipy.misc import factorial
ImportError: cannot import name 'factorial' from 'scipy.misc' (/home/robert/anaconda3/envs/prism/lib/python3.7/site-packages/scipy/misc/__init__.py)
```

![image](https://user-images.githubusercontent.com/5479894/94121171-5039e900-fe51-11ea-888d-97a4f190725e.png)

**Comment by SmokinCaterpillar** [comment]
Ok, nevermind, updating statsmodels solved the issue!
