### ISSUE TITLE
Issue with xarray dimensions

### ISSUE THREAD

**Issue by juanfcocontreras** [man-group/dtale#319]
With the following [xarray file](https://github.com/man-group/dtale/files/5567657/roi.nc.zip), I get the following exception when trying to access the xarray dimensions:

`ValueError: If using all scalar values, you must pass an index`

I think the problem is on line 2718 of the views.py file:

`dim = pd.DataFrame({"value": ds.coords[dim].data})`

And I think it would be enough to change it for the next one to fix it:

`dim = pd.Series({"value": ds.coords[dim].data}).to_frame()`

**Comment by aschonfeld** [comment]
@juanfcocontreras Thanks for catching this and I plan on adding this to the release this weekend.  Here's how I'll do it:
```python
@dtale.route("/xarray-dimension-values/<data_id>/<dim>")
@exception_decorator
def get_xarray_dimension_values(data_id, dim):
    ds = global_state.get_dataset(data_id)
    try:
        dim = pd.DataFrame({"value": ds.coords[dim].data})
    except ValueError:
        dim = pd.Series({"value": ds.coords[dim].data}).to_frame()
    dim_f, _ = build_formatters(dim)
    return jsonify(data=dim_f.format_dicts(dim.itertuples()))
```
Let me know if you're alright with that and I'll move forward 🙏

**Comment by juanfcocontreras** [comment]
After that arrangement, dtale gives another exception in:

```
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/conda-forge/lib/python3.7/site-packages/dtale/views.py", line 79, in _handle_exceptions
    return func(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/conda-forge/lib/python3.7/site-packages/dtale/views.py", line 2723, in get_xarray_dimension_values
    return jsonify(data=dim_f.format_dicts(dim.itertuples()))
  File "/usr/local/Caskroom/miniconda/base/envs/conda-forge/lib/python3.7/site-packages/dtale/utils.py", line 373, in format_dicts
    return list(map(self.format_dict, lsts))
  File "/usr/local/Caskroom/miniconda/base/envs/conda-forge/lib/python3.7/site-packages/dtale/utils.py", line 369, in format_dict
    for idx, name, f in self.fmts
  File "/usr/local/Caskroom/miniconda/base/envs/conda-forge/lib/python3.7/site-packages/dtale/utils.py", line 369, in <dictcomp>
    for idx, name, f in self.fmts
  File "/usr/local/Caskroom/miniconda/base/envs/conda-forge/lib/python3.7/site-packages/dtale/utils.py", line 323, in f
    return json_string(x)
  File "/usr/local/Caskroom/miniconda/base/envs/conda-forge/lib/python3.7/site-packages/dtale/utils.py", line 196, in json_string
    if pd.isnull(x):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by juanfcocontreras** [comment]
It's been a while since I've used dtale for xarray, but I think there have been several changes, probably in pandas that have affected its functionality.

If a single-point dataset is selected, it gives another exception:

```
poi = ds.isel(rlat=0, rlon=0)
show(poi)
```
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/conda-forge/lib/python3.7/site-packages/xarray/core/utils.py", line 542, in __len__
    return self.shape[0]
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/conda-forge/lib/python3.7/site-packages/dtale/views.py", line 79, in _handle_exceptions
    return func(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/conda-forge/lib/python3.7/site-packages/dtale/views.py", line 2709, in get_xarray_coords
    for coord, info in ds.coords.items()
  File "/usr/local/Caskroom/miniconda/base/envs/conda-forge/lib/python3.7/site-packages/dtale/views.py", line 2709, in <listcomp>
    for coord, info in ds.coords.items()
  File "/usr/local/Caskroom/miniconda/base/envs/conda-forge/lib/python3.7/site-packages/xarray/core/dataarray.py", line 555, in __len__
    return len(self.variable)
  File "/usr/local/Caskroom/miniconda/base/envs/conda-forge/lib/python3.7/site-packages/xarray/core/utils.py", line 544, in __len__
    raise TypeError("len() of unsized object")
TypeError: len() of unsized object
```

**Comment by aschonfeld** [comment]
Ok, thanks.  Maybe i’ll hold off on this release and dig back into xarray for the next one.  Thanks for your help

**Comment by aschonfeld** [comment]
@juanfcocontreras good news, I did some digging and the issue was with how I was obtaining the dimensions.  I was assuming that everything in `ds.coords` were dimensions, but what I really needed to be iterating was `ds.coords.dims`.  Now `lat` & `lon` won't show up as dimensions, which they shouldn't.  I'll have this ready for the release 👍

**Comment by juanfcocontreras** [comment]
That's great, thank you very much!

By the way, I don't know if to put it right here or open a new issue, when open_browser=True, it shouldn't appear dtale embedded in Jupyter (or nteract in my case), right? The browser is open, but still appears in the output of the cell.

**Comment by aschonfeld** [comment]
Hmm, I never actually tried doing `open_browser=True` in jupyter before.  It worked for me but left this cell behind it:
![image](https://user-images.githubusercontent.com/11547371/99887036-08480000-2c0f-11eb-93f6-0cf403757911.png)
I can see if I can update it to no longer create that extra cell in that case

**Comment by aschonfeld** [comment]
Ok I think I have a fix for that too

**Comment by juanfcocontreras** [comment]
Thas is awesome!! Thank you so much!!

PD: I've played a little bit with the xarray fix and it seems to work fine!

**Comment by aschonfeld** [comment]
Terrific, I'll let you know when I publish 1.23.0

**Comment by aschonfeld** [comment]
Ok v1.23.0 should be on conda in the next 15 minutes.  Just merged the version update

**Comment by juanfcocontreras** [comment]
Both fixes seem to be working great. Thank you very much!
