### ISSUE TITLE
unhashable type: 'Series'

### ISSUE THREAD

**Issue by proxseas** [man-group/dtale#551]
I am unable to do any advanced filtering. Given a test case where a data frame simply has a string column, it will still throw this error. Below is an example of what my test dataframe looks like:
![image](https://user-images.githubusercontent.com/13462108/129430946-9a0981d5-fe65-4165-b5cd-534881b1b2c5.png)

The custom filter I'm trying to use is something like this: `id.str.contains('abc')`. This will throw the following error:
`Exception occurred while processing request: unhashable type: 'Series'
Traceback (most recent call last):
  File "/home/hagen/miniconda3/lib/python3.9/site-packages/dtale/views.py", line 105, in _handle_exceptions
    return func(*args, **kwargs)
  File "/home/hagen/miniconda3/lib/python3.9/site-packages/dtale/views.py", line 1672, in test_filter
    run_query(
  File "/home/hagen/miniconda3/lib/python3.9/site-packages/dtale/query.py", line 65, in run_query
    df = df.query(
  File "/home/hagen/miniconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 4055, in query
    res = self.eval(expr, **kwargs)
  File "/home/hagen/miniconda3/lib/python3.9/site-packages/pandas/core/frame.py", line 4186, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/home/hagen/miniconda3/lib/python3.9/site-packages/pandas/core/computation/eval.py", line 353, in eval
    ret = eng_inst.evaluate()
  File "/home/hagen/miniconda3/lib/python3.9/site-packages/pandas/core/computation/engines.py", line 80, in evaluate
    res = self._evaluate()
  File "/home/hagen/miniconda3/lib/python3.9/site-packages/pandas/core/computation/engines.py", line 120, in _evaluate
    _check_ne_builtin_clash(self.expr)
  File "/home/hagen/miniconda3/lib/python3.9/site-packages/pandas/core/computation/engines.py", line 36, in _check_ne_builtin_clash
    names = expr.names
  File "/home/hagen/miniconda3/lib/python3.9/site-packages/pandas/core/computation/expr.py", line 833, in names
    return frozenset([self.terms.name])
TypeError: unhashable type: 'Series'`

Meanwhile a filter like this will work just fine: `id == 'abc'`. Note that I'm on the latest version of Conda and dtale. Please advise.

**Comment by aschonfeld** [comment]
@proxseas Hmm, so far I've tried:
* dataframes with a string column and other columns
* dataframes with only one column (a string column named `id`)
* on pandas 1.3.1 & 1.2.1

All seem to work fine.  The only nuance I've seen is when the string column in question contains NaN values.  Then you filter will have to be `id == id and id.str.contains('...')`

The `id == id` addition drops NaN values from the `contains` check.

So I guess my suggestion would be to try reinstalling pandas. Let me know how it goes. Good luck

**Comment by proxseas** [comment]
I actually just reinstalled Anaconda3. Prior to this, I was running Miniconda, in WSL Ubuntu, with various Jupyter-related packages that I installed manually. I wiped out my Miniconda installation and installed the full version of Anaconda3, followed by simply installing dtale with pip: "pip install dtale".
Then I created a simple dataframe:
```
import pandas as pd
import dtale

df = pd.DataFrame([
  dict(name='Joe', age=7),
  dict(name='Bob', age=23),
  dict(name='Ann', age=45),
  dict(name='Cat', age=88),
])
dtale.show(df, host='0.0.0.0')
```

With this simple test case, I've been able to verify that something is really broken here. As an example, I tried this filter:
```name.str.len() == 3```
And got the following error:
```
unhashable type: 'numpy.ndarray
Traceback (most recent call last):
  File "/home/hagen/anaconda3/lib/python3.8/site-packages/dtale/views.py", line 105, in _handle_exceptions
    return func(*args, **kwargs)
  File "/home/hagen/anaconda3/lib/python3.8/site-packages/dtale/views.py", line 2317, in get_data
    data = run_query(
  File "/home/hagen/anaconda3/lib/python3.8/site-packages/dtale/query.py", line 65, in run_query
    df = df.query(
  File "/home/hagen/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py", line 4055, in query
    res = self.eval(expr, **kwargs)
  File "/home/hagen/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py", line 4186, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/home/hagen/anaconda3/lib/python3.8/site-packages/pandas/core/computation/eval.py", line 353, in eval
    ret = eng_inst.evaluate()
  File "/home/hagen/anaconda3/lib/python3.8/site-packages/pandas/core/computation/engines.py", line 80, in evaluate
    res = self._evaluate()
  File "/home/hagen/anaconda3/lib/python3.8/site-packages/pandas/core/computation/engines.py", line 120, in _evaluate
    _check_ne_builtin_clash(self.expr)
  File "/home/hagen/anaconda3/lib/python3.8/site-packages/pandas/core/computation/engines.py", line 36, in _check_ne_builtin_clash
    names = expr.names
  File "/home/hagen/anaconda3/lib/python3.8/site-packages/pandas/core/computation/expr.py", line 834, in names
    return frozenset(term.name for term in com.flatten(self.terms))
TypeError: unhashable type: 'numpy.ndarray'
```

Meanwhile, running string filtering produces the common result `unhashable type: 'Series'`. E.g. query:
```name.str.contains('a', na=False, case=False)```

I wonder if this issue could be related to WSL, somehow. But I haven't had problems with running Pandas on it in the past.

**Comment by proxseas** [comment]
A quick update: I set up an Ubuntu VM and had the same set of errors take place. All using the latest version of Anaconda3 and this package. So it's definitely not related to WSL.

**Comment by aschonfeld** [comment]
I'll mucking around with conda and see if I can re-create the error.  So far no luck using a standard pip-based virtual environment

**Comment by proxseas** [comment]
Sounds good. For the record, I used this Anaconda installer: https://repo.anaconda.com/archive/Anaconda3-2021.05-Linux-x86_64.sh. I used a standard installation (all options at default), then ran 'pip install dtale'.

**Comment by aschonfeld** [comment]
Ok, maybe that is the problem.  I created a new conda environment `conda create -n dtale_39-0 python=3.9` then I ran `conda install dtale -c conda-forge`

Once that completed I opened a python terminal and ran the following:
```
import pandas as pd
import dtale

dtale.show(pd.DataFrame(dict(a=['foo', 'bar', 'baz'])))
```

Then when I got into the app I was able to add the filter `a.str.contains('f', na=False, case=False)` with no issues.

**Comment by proxseas** [comment]
Looks like that was the issue. I created yet another new environment and installed dtale and related dependencies using '-c conda-forge' and it worked. Thank you.
