### ISSUE TITLE
TypeError: 'input' object is not iterable

### ISSUE THREAD

**Issue by yuchaofan13** [man-group/dtale#554]
I try to run 'dtale.show(df)' but get this error message. Any help would be appreciated.

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\dtale\app.py", line 708, in _start
    app = build_app(
  File "C:\ProgramData\Anaconda3\lib\site-packages\dtale\app.py", line 474, in build_app
    app = dash_views.add_dash(app)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dtale\dash_application\views.py", line 131, in add_dash
    init_callbacks(dash_app)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dtale\dash_application\views.py", line 345, in init_callbacks
    @dash_app.callback(
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 950, in callback
    self._validate_callback(output, inputs, state)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 649, in _validate_callback
    for i in inputs:
TypeError: 'Input' object is not iterable

**Comment by yuchaofan13** [comment]
Forgot to mention I'm running jupyter notebook in VS code. It was working a few hours ago; the only change that happened in the interim I can think of is that I installed beautifulsoup and selenium.

**Comment by aschonfeld** [comment]
So, I wonder if dash has updated their API.  When creating callbacks you used to be able to specify a single input or a list of inputs.  Looks like based on your exception it now requires you to always specify a list of inputs.  I'm running dash 1.20.0 and its working fine.  That being said, I'm working on a new version of D-Tale which will always use a list of inputs.  I'll let you know when the new version has been released, but in the meantime you can try downgrading your version of dash if its newer than 1.20.0.

Apologies for the issue

**Comment by yuchaofan13** [comment]
Thanks a lot for the help, and also many thanks for developing dtale- I love it!

**Comment by aschonfeld** [comment]
@yuchaofan13 happy to hear it helps! If you havent already please toss your ⭐️ on the repo. Thanks 🙏

**Comment by aschonfeld** [comment]
Fixed in v1.56.0
