### ISSUE TITLE
DTale -Flask - Heroku - Gunicorn - Deployment problem

### ISSUE THREAD

**Issue by ShoubhikBanerjee** [man-group/dtale#575]
Hi !

I was trying to deploy a Heroku app build with Flask using Gunicorn. 

I have embedded flask as shown in : [https://github.com/man-group/dtale/blob/master/docs/EMBEDDED_FLASK.md](https://github.com/man-group/dtale/blob/master/docs/EMBEDDED_FLASK.md)

My Gunicorn  cmd : `web: gunicorn app:app --preload -b 0.0.0.0:8080`
But facing this issue : 

`Traceback (most recent call last):
   File "/app/.heroku/python/bin/gunicorn", line 8, in <module>
     sys.exit(run())
   File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
   File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/base.py", line 228, in run
     super().run()
   File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/base.py", line 72, in run
     Arbiter(self).run()
   File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 58, in __init__
     self.setup(app)
   File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/arbiter.py", line 118, in setup
     self.app.wsgi()
   File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
     self.callable = self.load()
   File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
     return self.load_wsgiapp()
   File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
     return util.import_app(self.app_uri)
   File "/app/.heroku/python/lib/python3.9/site-packages/gunicorn/util.py", line 405, in import_app
     raise AppImportError("Failed to find attribute %r in %r." % (name, module))
 gunicorn.errors.AppImportError: Failed to find attribute 'app' in 'app'.`

Is there any way I can get this solved ? 

Thanx in advance :)

**Comment by aschonfeld** [comment]
@ShoubhikBanerjee heres an [example](https://github.com/man-group/dtale/issues/475#issuecomment-839677610) of running D-Tale in gunicorn w/ redis for storage (so all gunicorn workers feed from the same data).  Not 100% sure if using Heroku will throw a wrench into things or not.  Let me know if this helps and if not I can dig into it deeper.
