### ISSUE TITLE
Issue with npm run build 

### ISSUE THREAD

**Issue by Balaguru16** [man-group/dtale#604]
Hi..I'm facing this issue while running dtale in my browser.

```
Traceback (most recent call last):
  File "/home/i_balagurum/anaconda3/envs/smart_eda_new/lib/python3.9/site-packages/Flask-2.0.2-py3.9.egg/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/i_balagurum/anaconda3/envs/smart_eda_new/lib/python3.9/site-packages/Flask-2.0.2-py3.9.egg/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/i_balagurum/anaconda3/envs/smart_eda_new/lib/python3.9/site-packages/Flask-2.0.2-py3.9.egg/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/i_balagurum/anaconda3/envs/smart_eda_new/lib/python3.9/site-packages/Flask-2.0.2-py3.9.egg/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/i_balagurum/Desktop/TICC/ticc_code/ticc_exp/dtale_final/dtale/dtale/views.py", line 1144, in view_iframe
    return _view_main(data_id, iframe=True)
  File "/home/i_balagurum/Desktop/TICC/ticc_code/ticc_exp/dtale_final/dtale/dtale/views.py", line 1101, in _view_main
    return base_render_template("dtale/main.html", data_id, title=title, iframe=iframe)
  File "/home/i_balagurum/Desktop/TICC/ticc_code/ticc_exp/dtale_final/dtale/dtale/views.py", line 1064, in base_render_template
    if not len(os.listdir("{}/static/dist".format(os.path.dirname(__file__)))):
FileNotFoundError: [Errno 2] No such file or directory: '/home/i_balagurum/Desktop/TICC/ticc_code/ticc_exp/dtale_final/dtale/dtale/static/dist'


```

And when I checked for solution,I came through this conversion
[https://github.com/man-group/dtale/issues/443]

According to that, I tried 

-     npm install
-     npm run build
- 
But, npm run build threw this error

`npm ERR! missing script: build`

complete log on the error was:

```
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.12
3 info using node@v12.22.1
4 verbose stack Error: missing script: build
4 verbose stack at run (/usr/lib/node_modules/npm/lib/run-script.js:155:19)
4 verbose stack at /usr/lib/node_modules/npm/lib/run-script.js:63:5
4 verbose stack at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:116:5
4 verbose stack at /usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:436:5
4 verbose stack at checkBinReferences_ (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:391:45)
4 verbose stack at final (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:434:3)
4 verbose stack at then (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:161:5)
4 verbose stack at ReadFileContext. (/usr/lib/node_modules/npm/node_modules/read-package-json/read-json.js:350:20)
4 verbose stack at ReadFileContext.callback (/usr/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:123:16)
4 verbose stack at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:261:13)
5 verbose cwd /home/i_balagurum/Desktop/TICC/ticc_code/ticc_exp/dtale_final/dtale
6 verbose Linux 4.15.0-153-generic
7 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
8 verbose node v12.22.1
9 verbose npm v6.14.12
10 error missing script: build
11 verbose exit [ 1, true ]
```

Please help me out,sir. Thanks :))

**Comment by aschonfeld** [comment]
@Balaguru16 apologies.  I think this might be an issue of out-of-date documentation.  I've been working for the last few weeks on converting the entire frontend codebase to typescript and one of the changes was to move all frontend code to a new `frontend` directory.  So I think the order of operation after you've cloned the D-Tale repo is the following:
```
# after you've navigated to the location of your cloned repo
$ cd frontend  
$ npm install
$ npm run build
```
Hope this helps & I'll update the documentation

**Comment by Balaguru16** [comment]
Yeah that helped..I'm now able to run my dtale instance.Thank you :))
