### ISSUE TITLE
Exception when rendering chart

### ISSUE THREAD

**Issue by gidim** [man-group/dtale#639]
I'm trying to render a line chart visualization and seeing this error:
```
Traceback (most recent call last):
File "lib\site-packages\dtale\dash_application\charts.py", line 3248, in build_chart
scatter_code = scatter_code_builder(data, x, y, axes_builder, **kwargs)
File "lib\site-packages\dtale\dash_application\charts.py", line 847, in scatter_code_builder
dict_merge(title, build_scatter_layout(axes_builder([y_val])[0], z))
File "lib\site-packages\dtale\dash_application\charts.py", line 348, in _build_axes
yaxis_cfg = dict(title=update_label_for_freq_and_agg(y), type=scale)
File "lib\site-packages\dtale\dash_application\layout\layout.py", line 661, in update_label_for_freq_and_agg
return ", ".join([_freq_handler(sub_val) for sub_val in make_list(val)])
File "lib\site-packages\dtale\dash_application\layout\layout.py", line 661, in
return ", ".join([_freq_handler(sub_val) for sub_val in make_list(val)])
File "lib\site-packages\dtale\dash_application\layout\layout.py", line 644, in _freq_handler
if sub_val.endswith("|{}".format(agg)):
AttributeError: 'NoneType' object has no attribute 'base64': "SGV5IEFuZHJldyEKU29ycnkgZm9yIG15IHVuaXF1ZSBtZXRob2RzIGJ1dCBob3BlIHlvdSBjYW4gYXBwcmVjaWF0ZSBzb21lIGNyZWF0aXZpdHkgOikgSSB0cmllZCBlbWFpbGluZyB5b3UgLyBMaW5rZWRpbiBhcyBJJ20gYSBodWdlIGZhbiBvZiBkLXRhbGUgYW5kIHRoaW5rIHRoZXJlJ3MgYSB1bmlxdWUgY29sbGFib3JhdGlvbiBvcHBvcnR1bml0eSB3aXRoIENvbWV0LiBXb3VsZCB5b3UgYmUgb3BlbiBmb3IgYSBxdWljayBjaGF0PyBoYXBweSB0byB3b3JrIGFyb3VuZCB5b3VyIHNjaGVkdWxlIGdpZGVvbkBjb21ldC5tbA=="
```

**Comment by aschonfeld** [comment]
Just out of curiosity, what version of D-Tale are you using?  Looks like the line numbers in your stacktrace are old.  Try upgrading `pip install -U dtale` and see if it fixes it.  Let me know if it works and if not I can dig in deeper.  Apologies for the issue

**Comment by aschonfeld** [comment]
Closing due to lack of information
