### ISSUE TITLE
Dtale flask server unexpectedly shutting down after time out period

### ISSUE THREAD

**Issue by richlysakowski** [man-group/dtale#662]
This has been happening regularly.  It is annoying because occasionally it loses data because it won't save after the timeout.  

Is there some setting that I can change to stop it from ever timing out?   I am running DTale locally only.  

**System Configuration:**

1. DTale Analysis Tool Version: 2.2.0
2. Pandas Analysis Tool Version: 1.4.2

#####################################################

Executing shutdown...
2022-04-22 16:38:44,648 - INFO     - Executing shutdown...
Exception on /shutdown [GET]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\sapio_migration\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\envs\sapio_migration\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\envs\sapio_migration\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\envs\sapio_migration\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\ProgramData\Anaconda3\envs\sapio_migration\lib\site-packages\dtale\app.py", line 410, in shutdown
    shutdown_server()
  File "C:\ProgramData\Anaconda3\envs\sapio_migration\lib\site-packages\dtale\app.py", line 396, in shutdown_server
    raise RuntimeError("Not running with the Werkzeug Server")
RuntimeError: Not running with the Werkzeug Server
2022-04-22 16:38:44,684 - ERROR    - Exception on /shutdown [GET]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\sapio_migration\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\envs\sapio_migration\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\envs\sapio_migration\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\envs\sapio_migration\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\ProgramData\Anaconda3\envs\sapio_migration\lib\site-packages\dtale\app.py", line 410, in shutdown
    shutdown_server()
  File "C:\ProgramData\Anaconda3\envs\sapio_migration\lib\site-packages\dtale\app.py", line 396, in shutdown_server
    raise RuntimeError("Not running with the Werkzeug Server")
RuntimeError: Not running with the Werkzeug Server

**Comment by aschonfeld** [comment]
@richlysakowski apologies for the issues.  D-Tale has a reaper process that kills a session after 60 minutes of inactivity.  If you want to turn off the reaper it can be done by adding `reaper_on=False` for example `dtale.show(df, reaper_on=False)`

If you don't want to specify that every time you call `dtale.show` then you can also use a global configuration file as detailed [here](https://github.com/man-group/dtale/blob/master/docs/CONFIGURATION.md) see `reaper_on` under the `[show]` section
