### ISSUE TITLE
Warning when calling dtale.show() multiple time within 1 Juypter session

### ISSUE THREAD

**Issue by ys-1234** [man-group/dtale#716]
When calling dtale.show() multiple time within 1 Juypter session, I see the warning below. The warning won't affect the actual functionality of Dtale. A new instance of Dtale will still be displayed appropriately. 
```
Exception ignored in thread started by: <function show.<locals>._start at 0x7f5c45d3d670>
Traceback (most recent call last):
  File "/dev/env/dtale/lib/python3.8/site-packages/dtale/app.py", line 799, in _start
    app.run(
  File "/dev/env/dtale/env/mlflow/lib/python3.8/site-packages/dtale/app.py", line 217, in run
    super(DtaleFlask, self).run(
  File "/dev/env/dtale/lib/python3.8/site-packages/flask/app.py", line 990, in run
    run_simple(host, port, self, **options)
  File "/dev/env/dtale/lib/python3.8/site-packages/werkzeug/serving.py", line 1052, in run_simple
    inner()
  File "/dev/env/dtale/lib/python3.8/site-packages/werkzeug/serving.py", line 996, in inner
    srv = make_server(
  File "/dev/env/dtale/lib/python3.8/site-packages/werkzeug/serving.py", line 847, in make_server
    return ThreadedWSGIServer(
  File "/dev/env/dtale/lib/python3.8/site-packages/werkzeug/serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/local/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/local/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/local/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

Is the warning intended? Or did I miss anything? Thanks!

**Comment by aschonfeld** [comment]
Hmm, so it shouldn't be throwing that error.  There is code that runs to check and see if there is a D-Tale instance running, but I wonder if that's not working correctly since you're in jupyter.  So the way to add an additional instance to D-Tale without seeing that error would be:
```
from dtale.views import startup

startup(data=new_df)
```

I'll keep digging to see if I can fix the `dtale.show` behavior

**Comment by aschonfeld** [comment]
Interesting, the error doesn't occur for me when running D-Tale with `jupyter notebook` on python3.8: 
![image](https://user-images.githubusercontent.com/11547371/209448191-bf8d3192-ae3e-4827-8c3f-8b9ee19f8d83.png)

**Comment by ys-1234** [comment]
Hi @aschonfeld thanks for the reply.

I tried ```startup(data=new_df)``` but I received the error `404 : Not Found You are requesting a page that does not exist!` 

I'm wondering if the warning is specific to some version of the python packages.
Here is my setting:
```
dtale 2.8.1
Python 3.8.6
Flask 1.1.4
Werkzeug 1.0.1
ipykernel  6.18.3
ipywidgets 8.0.2
jupyter_client  7.4.8
jupyter_core 5.1.0
jupyter_server 1.23.3
jupyterlab 3.5.2
```

And I tried both ```jupyter lab``` and ```jupyter notebook```. Both rendered the same behavior.

**Comment by aschonfeld** [comment]
@ys-1234 any chance this is the same docker issue from [here](https://github.com/man-group/dtale/issues/720)?

**Comment by aschonfeld** [comment]
Closing due to lack of activity
