### ISSUE TITLE
Unable to install on M2 with Ventura

### ISSUE THREAD

**Issue by karanrajpal14** [man-group/dtale#762]
I've been trying to move all of my projects from my old macbook with an i5 to my new machine and this is what I see.

I tried all the suggestions mentioned [here](https://stackoverflow.com/questions/65745683/how-to-install-scipy-on-apple-silicon-arm-m1) but none of them helped. Does anyone else have an idea about what's going on?

```sh
❯ pip install dtale
Looking in indexes: http://pypi.python.org/simple/
Collecting dtale
  Using cached http://pypi.python.org/packages/2d/65/5d44c9968bac1014a1a9ad2e7b6ee5c5fa7850a9dd421f40c72252c5135c/dtale-2.16.0-py2.py3-none-any.whl (14.0 MB)
Collecting dash-colorscales (from dtale)
  Using cached http://pypi.python.org/packages/d5/24/de9318acd52989d77135a8497c8be536442b725473684ed4e1ab999b2051/dash_colorscales-0.0.4.tar.gz (62 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting dash-daq (from dtale)
  Using cached http://pypi.python.org/packages/16/c1/9c6adfc3646990965a5b2ca073f579cc9c09d15553fcfcd83aefd1255494/dash_daq-0.5.0.tar.gz (642 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Flask-Compress (from dtale)
  Using cached http://pypi.python.org/packages/20/80/8cdb28e467d3ffdc221992145114a709c1e7c011b84c66bc250e27596286/Flask_Compress-1.13-py3-none-any.whl (7.9 kB)
Collecting future>=0.14.0 (from dtale)
  Using cached http://pypi.python.org/packages/8f/2e/cf6accf7415237d6faeeebdc7832023c90e0282aa16fd3263db0eb4715ec/future-0.18.3.tar.gz (840 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting kaleido (from dtale)
  Using cached http://pypi.python.org/packages/45/8e/4297556be5a07b713bb42dde0f748354de9a6918dee251c0e6bdcda341e7/kaleido-0.2.1-py2.py3-none-macosx_11_0_arm64.whl (85.8 MB)
Collecting missingno<=0.4.2 (from dtale)
  Using cached http://pypi.python.org/packages/2b/de/6e4dd6d720c49939544352155dc06a08c9f7e4271aa631a559dfbeaaf9d4/missingno-0.4.2-py3-none-any.whl (9.7 kB)
Requirement already satisfied: pandas in ./venv/lib/python3.7/site-packages (from dtale) (1.3.5)
Collecting squarify (from dtale)
  Using cached http://pypi.python.org/packages/0b/2b/2e77c35326efec19819cd1d729540d4d235e6c2a3f37658288a363a67da5/squarify-0.4.3-py3-none-any.whl (4.3 kB)
Collecting strsimpy (from dtale)
  Using cached http://pypi.python.org/packages/fc/90/bd55a4b18f4b75a76e32f444975d2c869d692eb23897d116d47122f88d1a/strsimpy-0.2.1-py3-none-any.whl (45 kB)
Requirement already satisfied: six in ./venv/lib/python3.7/site-packages (from dtale) (1.16.0)
Collecting xlrd (from dtale)
  Using cached http://pypi.python.org/packages/a6/0c/c2a72d51fe56e08a08acc85d13013558a2d793028ae7385448a6ccdfae64/xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
Collecting Flask<2.3 (from dtale)
  Using cached http://pypi.python.org/packages/9f/1a/8b6d48162861009d1e017a9740431c78d860809773b66cac220a11aa3310/Flask-2.2.5-py3-none-any.whl (101 kB)
Collecting matplotlib<=3.5.3 (from dtale)
  Using cached http://pypi.python.org/packages/02/81/e8276ec6ca005b3b2bfaaad0ea47dbb3a0e389ec8ab87d08e3ccbe4b2742/matplotlib-3.5.3.tar.gz (35.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting networkx<=2.6.3 (from dtale)
  Using cached http://pypi.python.org/packages/e9/93/aa6613aa70d6eb4868e667068b5a11feca9645498fd31b954b6c4bb82fa5/networkx-2.6.3-py3-none-any.whl (1.9 MB)
Collecting packaging<=21.0 (from dtale)
  Using cached http://pypi.python.org/packages/3c/77/e2362b676dc5008d81be423070dd9577fa03be5da2ba1105811900fda546/packaging-21.0-py3-none-any.whl (40 kB)
Collecting scikit-learn<=1.0.2 (from dtale)
  Using cached http://pypi.python.org/packages/75/44/074b780d8ac0b0899937e9b8ba6d5d8873a71b99aa915219251ef85a8890/scikit-learn-1.0.2.tar.gz (6.7 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [254 lines of output]
      Looking in indexes: http://pypi.python.org/simple
      Ignoring oldest-supported-numpy: markers 'python_version != "3.7" or platform_machine == "aarch64" or platform_system == "AIX" or platform_python_implementation == "PyPy"' don't match your environment
      Collecting setuptools<60.0
        Using cached http://pypi.python.org/packages/8d/25/88b377b99ffb4ad0fc44ff5735fd6be605b2183f743d1ff5c10b7790cea5/setuptools-59.8.0-py3-none-any.whl (952 kB)
      Collecting wheel
        Using cached http://pypi.python.org/packages/61/86/cc8d1ff2ca31a312a25a708c891cf9facbad4eae493b3872638db6785eb5/wheel-0.40.0-py3-none-any.whl (64 kB)
      Collecting Cython>=0.28.5
        Using cached http://pypi.python.org/packages/d2/49/9845f14b6716614c832535b67e3b491434d7fdecf510fcb6fe254f60a974/Cython-0.29.34-py2.py3-none-any.whl (988 kB)
      Collecting numpy==1.14.6
        Using cachedhttp://pypi.python.org/packages/86/c2/84dc6f58171bca90326f71e098438b87aa0c0d4a21bceda9caba2af6554e/numpy-1.14.6.zip (4.9 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): still running...
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting scipy>=1.1.0
        Using cached http://pypi.python.org/packages/61/67/1a654b96309c991762ee9bc39c363fc618076b155fe52d295211cf2536c7/scipy-1.7.3.tar.gz (36.1 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Preparing metadata (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [214 lines of output]
            Running scipy/linalg/_generate_pyx.py
            Running scipy/special/_generate_pyx.py
            Running scipy/stats/_generate_pyx.py
            Processing scipy/cluster/_vq.pyx
            Processing scipy/cluster/_optimal_leaf_ordering.pyx
            Processing scipy/cluster/_hierarchy.pyx
            Processing scipy/ndimage/src/_cytest.pyx
            Processing scipy/ndimage/src/_ni_label.pyx
            Processing scipy/linalg/cython_lapack.pyx
            Processing scipy/linalg/_matfuncs_sqrtm_triu.pyx
            Processing scipy/linalg/_solve_toeplitz.pyx
            Processing scipy/linalg/cython_blas.pyx
            Processing scipy/linalg/_decomp_update.pyx.in
            Processing scipy/optimize/_group_columns.pyx
            Processing scipy/optimize/_bglu_dense.pyx
            Processing scipy/optimize/_trlib/_trlib.pyx
            Processing scipy/optimize/_highs/cython/src/_highs_constants.pyx
            Processing scipy/optimize/_highs/cython/src/_highs_wrapper.pyx
            Processing scipy/optimize/_lsq/givens_elimination.pyx
            Processing scipy/optimize/cython_optimize/_zeros.pyx.in
            Processing scipy/io/matlab/mio_utils.pyx
            Processing scipy/io/matlab/streams.pyx
            Processing scipy/io/matlab/mio5_utils.pyx
            Processing scipy/_lib/_ccallback_c.pyx
            Processing scipy/_lib/_test_deprecation_def.pyx
            Processing scipy/_lib/_test_deprecation_call.pyx
            Processing scipy/_lib/messagestream.pyx
            Processing scipy/special/_ufuncs_cxx.pyx
            Processing scipy/special/cython_special.pyx
            Processing scipy/special/_ellip_harm_2.pyx
            Processing scipy/special/_comb.pyx
            Processing scipy/special/_test_round.pyx
            Processing scipy/special/_ufuncs.pyx
            Processing scipy/fftpack/convolve.pyx
            Processing scipy/interpolate/interpnd.pyx
            Processing scipy/interpolate/_bspl.pyx
            Processing scipy/interpolate/_ppoly.pyx
            Processing scipy/sparse/_csparsetools.pyx.in
            Processing scipy/sparse/csgraph/_shortest_path.pyx
            Processing scipy/sparse/csgraph/_traversal.pyx
            Processing scipy/sparse/csgraph/_flow.pyx
            Processing scipy/sparse/csgraph/_tools.pyx
            Processing scipy/sparse/csgraph/_matching.pyx
            Processing scipy/sparse/csgraph/_reordering.pyx
            warning: _cython_special_custom.pxi:9:8: Unreachable code
            warning: _cython_special_custom.pxi:13:4: Unreachable code
            warning: _cython_special_custom.pxi:21:8: Unreachable code
            warning: _cython_special_custom.pxi:25:4: Unreachable code
            warning: _cython_special_custom.pxi:33:8: Unreachable code
            warning: _cython_special_custom.pxi:37:4: Unreachable code
            warning: _cython_special_custom.pxi:45:8: Unreachable code
            warning: _cython_special_custom.pxi:49:4: Unreachable code
            Processing scipy/sparse/csgraph/_min_spanning_tree.pyx
            Processing scipy/spatial/ckdtree.pyx
            Processing scipy/spatial/_voronoi.pyx
            Processing scipy/spatial/_hausdorff.pyx
            Processing scipy/spatial/qhull.pyx
            Processing scipy/spatial/transform/rotation.pyx
            Processing scipy/signal/_max_len_seq_inner.pyx
            Processing scipy/signal/_peak_finding_utils.pyx
            Processing scipy/signal/_upfirdn_apply.pyx
            Processing scipy/signal/_spectral.pyx
            Processing scipy/signal/_sosfilt.pyx
            Processing scipy/stats/_stats.pyx
            Processing scipy/stats/_qmc_cy.pyx
            Processing scipy/stats/_sobol.pyx
            Processing scipy/stats/biasedurn.pyx
            Processing scipy/stats/_boost/src/beta_ufunc.pyx
            Processing scipy/stats/_boost/src/nbinom_ufunc.pyx
            Processing scipy/stats/_boost/src/binom_ufunc.pyx
            Cythonizing sources
            lapack_opt_info:
            lapack_mkl_info:
            customize UnixCCompiler
              libraries mkl_rt not found in ['.../venv/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE
      
            openblas_lapack_info:
            customize UnixCCompiler
            customize UnixCCompiler
              libraries openblas not found in ['.../venv/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE
      
            openblas_clapack_info:
            customize UnixCCompiler
            customize UnixCCompiler
              libraries openblas,lapack not found in ['.../venv/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE
      
            atlas_3_10_threads_info:
            Setting PTATLAS=ATLAS
            customize UnixCCompiler
              libraries lapack_atlas not found in .../venv/lib
            customize UnixCCompiler
              libraries tatlas,tatlas not found in .../venv/lib
            customize UnixCCompiler
              libraries lapack_atlas not found in /usr/local/lib
            customize UnixCCompiler
              libraries tatlas,tatlas not found in /usr/local/lib
            customize UnixCCompiler
              libraries lapack_atlas not found in /usr/lib
            customize UnixCCompiler
              libraries tatlas,tatlas not found in /usr/lib
            <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
              NOT AVAILABLE
      
            atlas_3_10_info:
            customize UnixCCompiler
              libraries lapack_atlas not found in .../venv/lib
            customize UnixCCompiler
              libraries satlas,satlas not found in .../venv/lib
            customize UnixCCompiler
              libraries lapack_atlas not found in /usr/local/lib
            customize UnixCCompiler
              libraries satlas,satlas not found in /usr/local/lib
            customize UnixCCompiler
              libraries lapack_atlas not found in /usr/lib
            customize UnixCCompiler
              libraries satlas,satlas not found in /usr/lib
            <class 'numpy.distutils.system_info.atlas_3_10_info'>
              NOT AVAILABLE
      
            atlas_threads_info:
            Setting PTATLAS=ATLAS
            customize UnixCCompiler
              libraries lapack_atlas not found in .../venv/lib
            customize UnixCCompiler
              libraries ptf77blas,ptcblas,atlas not found in .../venv/lib
            customize UnixCCompiler
              libraries lapack_atlas not found in /usr/local/lib
            customize UnixCCompiler
              libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
            customize UnixCCompiler
              libraries lapack_atlas not found in /usr/lib
            customize UnixCCompiler
              libraries ptf77blas,ptcblas,atlas not found in /usr/lib
            <class 'numpy.distutils.system_info.atlas_threads_info'>
              NOT AVAILABLE
      
            atlas_info:
            customize UnixCCompiler
              libraries lapack_atlas not found in .../venv/lib
            customize UnixCCompiler
              libraries f77blas,cblas,atlas not found in .../venv/lib
            customize UnixCCompiler
              libraries lapack_atlas not found in /usr/local/lib
            customize UnixCCompiler
              libraries f77blas,cblas,atlas not found in /usr/local/lib
            customize UnixCCompiler
              libraries lapack_atlas not found in /usr/lib
            customize UnixCCompiler
              libraries f77blas,cblas,atlas not found in /usr/lib
            <class 'numpy.distutils.system_info.atlas_info'>
              NOT AVAILABLE
      
            accelerate_info:
              NOT AVAILABLE
      
            lapack_info:
            customize UnixCCompiler
              libraries lapack not found in ['.../venv/lib', '/usr/local/lib', '/usr/lib']
              NOT AVAILABLE
      
            lapack_src_info:
              NOT AVAILABLE
      
              NOT AVAILABLE
      
            setup.py:493: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /private/var/folders/jw/48h69j15191gft9wgx4yz1sc0000gq/T/pip-modern-metadata-aqb8eqmp'), proceeding with generating Cython sources and expanding templates
              ' '.join(sys.argv[1:])))
            Running from SciPy source directory.
            /private/var/folders/jw/48h69j15191gft9wgx4yz1sc0000gq/T/pip-build-env-ltdddp4h/overlay/lib/python3.7/site-packages/numpy/distutils/system_info.py:639: UserWarning:
                Atlas (http://math-atlas.sourceforge.net/) libraries not found.
                Directories to search for the libraries can be specified in the
                numpy/distutils/site.cfg file (section [atlas]) or by setting
                the ATLAS environment variable.
              self.calc_info()
            /private/var/folders/jw/48h69j15191gft9wgx4yz1sc0000gq/T/pip-build-env-ltdddp4h/overlay/lib/python3.7/site-packages/numpy/distutils/system_info.py:639: UserWarning:
                Lapack (http://www.netlib.org/lapack/) libraries not found.
                Directories to search for the libraries can be specified in the
                numpy/distutils/site.cfg file (section [lapack]) or by setting
                the LAPACK environment variable.
              self.calc_info()
            /private/var/folders/jw/48h69j15191gft9wgx4yz1sc0000gq/T/pip-build-env-ltdddp4h/overlay/lib/python3.7/site-packages/numpy/distutils/system_info.py:639: UserWarning:
                Lapack (http://www.netlib.org/lapack/) sources not found.
                Directories to search for the sources can be specified in the
                numpy/distutils/site.cfg file (section [lapack_src]) or by setting
                the LAPACK_SRC environment variable.
              self.calc_info()
            Traceback (most recent call last):
              File ".../venv/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
                main()
              File ".../venv/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
              File ".../venv/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
                return hook(metadata_directory, config_settings)
              File "/private/var/folders/jw/48h69j15191gft9wgx4yz1sc0000gq/T/pip-build-env-ltdddp4h/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 166, in prepare_metadata_for_build_wheel
                self.run_setup()
              File "/private/var/folders/jw/48h69j15191gft9wgx4yz1sc0000gq/T/pip-build-env-ltdddp4h/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 259, in run_setup
                self).run_setup(setup_script=setup_script)
              File "/private/var/folders/jw/48h69j15191gft9wgx4yz1sc0000gq/T/pip-build-env-ltdddp4h/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 150, in run_setup
                exec(compile(code, __file__, 'exec'), locals())
              File "setup.py", line 631, in <module>
                setup_package()
              File "setup.py", line 627, in setup_package
                setup(**metadata)
              File "/private/var/folders/jw/48h69j15191gft9wgx4yz1sc0000gq/T/pip-build-env-ltdddp4h/overlay/lib/python3.7/site-packages/numpy/distutils/core.py", line 137, in setup
                config = configuration()
              File "setup.py", line 529, in configuration
                raise NotFoundError(msg)
            numpy.distutils.system_info.NotFoundError: No BLAS/LAPACK libraries found. Note: Accelerate is no longer supported.
            To build Scipy from sources, BLAS & LAPACK libraries need to be installed.
            See site.cfg.example in the Scipy source directory and
            https://docs.scipy.org/doc/scipy/reference/building/index.html for details.
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
      
      × Encountered error while generating package metadata.
      ╰─> See above for output.
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Here are the necessary details:
```sh
❯ python -VV
Python 3.7.16 (default, May 23 2023, 12:52:03)
[Clang 14.0.3 (clang-1403.0.22.14.1)]

❯ pip -V
pip 23.1.2 from ~/..../venv/lib/python3.7/site-packages/pip (python 3.7)

❯ neofetch
                    'c.          xxxxxx@xxxxxxxxxxxxx.tld
                 ,xNMM.          ---------------------
               .OMMMMo           OS: macOS 13.4 22F66 arm64
               OMMM0,            Host: Mac14,7
     .;loddo:' loolloddol;.      Kernel: 22.5.0
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 20 hours, 11 mins
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 135 (brew)
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: fish 3.6.1
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1920x1080
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Dark)
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: iTerm2
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   Terminal Font: Monaco 12
    kMMMMMMMMMMMMMMMMMMMMMMd     CPU: Apple M2
     ;KMMMMMMMWXXWMMMMMMMk.      GPU: Apple M2
       .cooc,.    .,coo:.        Memory: 2731MiB / 16384MiB
```

Any suggestions would be helpful. Thank you!

**Comment by aschonfeld** [comment]
@karanrajpal14 can you try just running? `pip install scikit-learn` I want to see if it will allow you to install scikit-learn separately. If it does then I might need to tweaking the requirements.  If it does install, please send over which version it installed.  Thanks 🙏

**Comment by aschonfeld** [comment]
Oh wait sorry, I just read over that stackoverflow post you mentioned and it appears you probably did this already.  Try doing what they mention [here](https://github.com/scipy/scipy/issues/9005#issuecomment-623528512)
