### ISSUE TITLE
Column names contain "|"

### ISSUE THREAD

**Issue by HernandoMV** [man-group/dtale#788]
The column names in my dataframe already contain the pipe symbol. I am getting the following error trying to generate charts:

```
Traceback (most recent call last):
  File "/home/hernando/anaconda3/envs/dev/lib/python3.10/site-packages/dtale/dash_application/charts.py", line 3804, in build_chart
    data, code = build_figure_data(data_id, data=data, **inputs)
  File "/home/hernando/anaconda3/envs/dev/lib/python3.10/site-packages/dtale/dash_application/charts.py", line 3634, in build_figure_data
    data, chart_code = build_base_chart(data, x, y, unlimited_data=True, **chart_kwargs)
  File "/home/hernando/anaconda3/envs/dev/lib/python3.10/site-packages/dtale/charts/utils.py", line 728, in build_base_chart
    data, code = retrieve_chart_data(
  File "/home/hernando/anaconda3/envs/dev/lib/python3.10/site-packages/dtale/charts/utils.py", line 350, in retrieve_chart_data
    s, code = freq_handler(col)
  File "/home/hernando/anaconda3/envs/dev/lib/python3.10/site-packages/dtale/charts/utils.py", line 174, in _handler
    if len(col_def_segs) > 1 and classify_type(dtypes[col_def_segs[0]]) == "D":
KeyError: 'FOV'
```

![image](https://github.com/man-group/dtale/assets/6049065/33a2bcdc-b49f-48db-8350-a9e0b5ea7286)

Any way to use dTale for my datasets that does not imply renaming the columns?

Cheers

**Comment by aschonfeld** [comment]
This change has been added in v3.4.0 of D-Tale.  It has been released to pypi and should be on conda-forge shortly. Let me know if you have any issues.

Also, if you haven't already, please put your ⭐ on the repo when you get a sec. Thanks! 🙏
